### ISSUE TITLE
arcface model is invalid

### ISSUE THREAD

**Issue by snnn** [onnx/models#91]
I downloaded the model from:
https://s3.amazonaws.com/onnx-model-zoo/arcface/resnet100/resnet100.onnx

If you open the model, take a look at the second OP: Sub. Its first input, A, is a float tensor, but its second input, B, is a double tensor.

**Comment by snnn** [comment]
Hi @ankkhedia 

It's float64 ?

**Comment by prasanthpul** [comment]
@ankkhedia your screenshot shows it as a float64 (aka double) which doesn't seem to be supported by https://github.com/onnx/onnx/blob/master/docs/Operators.md#Sub. In fact none of the ops seem to list float64 as supported inputs.

**Comment by prasanthpul** [comment]
@snnn is the problem that the type needs to be the same for both?

**Comment by prasanthpul** [comment]
@ankkhedia can you fix the model?

**Comment by ankkhedia** [comment]
@prasanthpul I will take a look.

**Comment by prasanthpul** [comment]
@ankkhedia any update on this?

**Comment by ankkhedia** [comment]
Hi @prasanthpul Sorry for being late as got pulled into some other things. I will try to prioritise it this week.

**Comment by linkerzhang** [comment]
This is not good. We'd remove these models if they're invalid. We can add them back after fixing those issues.

@snnn  are there more model issues you saw please? Thank you very much for bringing this up!

**Comment by linkerzhang** [comment]
@ankkhedia

**Comment by snnn** [comment]
@ankkhedia  Any update? Could you please confirm if these models have problems?

Thanks

**Comment by ankkhedia** [comment]
I will check other models. However, Arcface issue has been fixed and I will update the new model.

**Comment by ankkhedia** [comment]
Hi @snnn Could you please point to the problems with the above models you listed so that I can take a look.

**Comment by snnn** [comment]
The inputs to GEMM operator, are not 2D tensors. They have more than 2 dimensions.

**Comment by snnn** [comment]
Hi @ankkhedia After downloading the latest Arcface model, I'm getting a new error:

 Type parameter (T) bound to different types (tensor(float) and tensor(double) in node (_minusscalar0).

**Comment by snnn** [comment]
Hi @ankkhedia , do you have an estimated time of completion?

**Comment by ankkhedia** [comment]
@snnn I will have to check with ONNX-MXNet converter team to be able to give a clear ETA.
I will update you on the same.
If the support has not been added, then it depends upon their roadmap on when the support will be complete. The team is working actively to get rigorous operator coverage.

**Comment by prasanthpul** [comment]
@ankkhedia I think your last comment is about the other models. can you confirm whether arcface model has been fixed? Will you be posting a 1.3 version as well?

**Comment by snnn** [comment]
The issue was already there 3 months, but we still don't know when it can be fixed?
From user experience perspective, ONNX user would think ONNX model zoo is low quality. I suggest we either fix it quickly, or delete the malformed models.

**Comment by prasanthpul** [comment]
@snnn lets create separate issue for the other models. this issue is only for arcface.
for the other models, I agree that if we cannot fix them they should be removed for now.

**Comment by ankkhedia** [comment]
@snnn @prasanthpul The model has been fixed and updated in the S3. I checked the model structure with Netron and float64 is not there anymore.

**Comment by prasanthpul** [comment]
Thanks @ankkhedia. Looks like only 1.2 (opset7) version is posted. will you be posting 1.3 as well?

**Comment by snnn** [comment]
Hi @ankkhedia , could please verify it?
I got the model from:
'https://s3.amazonaws.com/onnx-model-zoo/arcface/resnet100/resnet100.tar.gz'

It is still wrong.

**Comment by ankkhedia** [comment]
@snnn Sorry for the miss. I uploaded renet100.onnx file I will change this tar too

**Comment by ankkhedia** [comment]
@snnn added the latest tar file.

**Comment by ryanlai2** [comment]
Can we also modify ArcFace's README.md so that the table to download the model is correct?

Currently, there is only one download link for ArcFace and it's labeled as OpSet 7, v1.2.1. However, the link downloads an OpSet8 v1.3 version of the model.
https://github.com/onnx/models/tree/master/models/face_recognition/ArcFace

![image](https://user-images.githubusercontent.com/16694211/48521148-1c8ae280-e828-11e8-8105-56435368d1fe.png)

**Comment by ankkhedia** [comment]
updated :)

**Comment by snnn** [comment]
Hi @ankkhedia , the old issue is fixed, but we get new one.  
For the "relu0" node, its inputs has shape of [1, 64, 112, 112] and [64].  There is no broadcast rule can be applied on them.

**Comment by snnn** [comment]
Hi @ankkhedia , Could you verify issue?

Thanks.

**Comment by Roshrini** [comment]
Hi @snnn, I verified this issue on my end. We are actively working on both Prelu and Gemm issue mentioned and re-upload the models as early as we can. Thanks for reporting this and sorry for the inconvenience it has caused.

**Comment by ankkhedia** [comment]
Hi @snnn There are open PR to fix the above issues with Prelu and GEMM.
I have generated a model after including those fixes https://s3.amazonaws.com/onnx-model-zoo/arcface/resnet100/resnet100_new.onnx 
Could you please let me know if this model looks good to you. 

We will update the model once the PR are merged.

**Comment by MitchVonk** [comment]
I would suggest you update this new model to the Zoo aswell

**Comment by snnn** [comment]
Hi @ankkhedia , would you please put the new model in  https://github.com/onnx/models/tree/master/models/face_recognition/ArcFace ?

**Comment by ankkhedia** [comment]
I have updated the model in https://s3.amazonaws.com/onnx-model-zoo/arcface/resnet100/resnet100.onnx

Could you please verify?

**Comment by snnn** [comment]
Hi @ankkhedia 
https://s3.amazonaws.com/onnx-model-zoo/arcface/resnet100/resnet100.tar.gz is not updated.

**Comment by ankkhedia** [comment]
My bad. Updating the same

**Comment by snnn** [comment]
And this https://s3.amazonaws.com/onnx-model-zoo/arcface/resnet100/resnet100-md5.txt ?

**Comment by ankkhedia** [comment]
@snnn 
uploaded resnet100.tar.gz and resnet100-md5.txt now.

**Comment by snnn** [comment]
Perfect. Thanks!

**Comment by XinyuDu** [comment]
@ankkhedia Hi, How can convert the arcface mxnet model to onnx model without the float64 error? THX!

**Comment by luan1412167** [comment]
@snnn @ankkhedia I get the error. It may be same as your error. Have Any your experiment help me? Thanks
`2019-10-08 11:49:13.612837502 [E:onnxruntime:, sequential_executor.cc:165 Execute] Non-zero status code returned while running PRelu node. Name:'relu0' Status Message: /home/luandd/project_company/face_rec/onnxruntime/onnxruntime/core/providers/cpu/math/element_wise_ops.h:329 void onnxruntime::BroadcastIterator::Init(int64_t, int64_t) axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 64 by 112
`

**Comment by luan1412167** [comment]
@snnn @ankkhedia have you right model with spatial=1?

**Comment by sky186** [comment]
@ankkhedia 
hello , arcface mxnet to onnx canbe fixed?
how to convert onnx ,is right?
the prelu out not right? because Iwant to convert caffe,but the onnx can be export but is not right?

**Comment by sky186** [comment]
@luan1412167 
hi, now youcan convert mxnet arcface to onnx right ?   I fix ,but export model prelu out not right,not to equal mxnet,could you tell me how to convert onnx right ?

**Comment by HoangTienDuc** [comment]
> Hi @ankkhedia , the old issue is fixed, but we get new one.
> For the "relu0" node, its inputs has shape of [1, 64, 112, 112] and [64]. There is no broadcast rule can be applied on them.

hi @ankkhedia  @snnn i also try to convert arcface LResNet100E-IR [mxnet](https://github.com/deepinsight/insightface/wiki/Model-Zoo) to onnx by using [convert_onnx.py](https://github.com/deepinsight/insightface/tree/master/deploy). Then, it seem that, i got the same error with @snnn when i deploy my model.
```
onnx runtime error 1: Non-zero status code returned while running PRelu node. Name:'relu0' Status Message: relu0: right operand cannot broadcast on dim 0 LeftShape: {1,64,112,112}, RightShape: {64}
```
Can you guide me how to fix it? 
Thank all off u.

**Comment by snnn** [comment]
see #17711

@vinitra is fixing it.
